# Generated by Django 5.2.16 on 2026-07-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGerakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gerakan', models.CharField(max_length=50)),
                ('sudut_maksimal', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('wajib_scapular_plane', models.BooleanField(default=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Master Gerakan',
                'verbose_name_plural': 'Master Gerakan',
                'ordering': ['nama_gerakan'],
            },
        ),
        migrations.CreateModel(
            name='SesiLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True)),
                ('total_reps', models.IntegerField(default=0)),
                ('total_form_error', models.IntegerField(default=0)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('gerakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesi.mastergerakan')),
            ],
            options={
                'verbose_name': 'Sesi Latihan',
                'verbose_name_plural': 'Riwayat Sesi Latihan',
                'ordering': ['-waktu_mulai'],
            },
        ),
    ]
