# Generated by Django 5.2.16 on 2026-07-29 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesilatihan',
            name='klien',
            field=models.ForeignKey(limit_choices_to={'role': 'klien'}, on_delete=django.db.models.deletion.CASCADE, related_name='sesi_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
